server:
  port: 8084
spring:
  application:
    name: user-service # 微服务名称
  cloud:
    nacos:
      server-addr: 192.168.19.129:8848 # nacos地址
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3307/hm-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug # 前面是包名，即com.hmall下的所有类的日志级别都是debug
  pattern:
    dateformat: HH:mm:ss:SSS # 日期格式
  file:
    path: "logs/${spring.application.name}" # 日志文件路径
knife4j:
  enable: true
  openapi:
    title: 黑马商城用户接口文档
    description: "黑马商城用户接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.user.controller
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
