server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  db:
    database: hm-cart
    swagger:
      title: "黑马商城购物车接口文档"
      desc: "黑马商城购物车接口文档"
      package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 106.14.144.133:8090 # sentinel控制台地址
        clientIp: 106.14.144.133 # 本地公网ip
      http-method-specify: true # 开启请求方式前缀